
    name: tp0
    services:
        server:
            container_name: server
            image: server:latest
            entrypoint: python3 /main.py
            environment:
                - PYTHONUNBUFFERED=1
            volumes:
                - ./server/config.ini:/config.ini:ro
            networks:
                - testing_net
    
        client1:
            container_name: client1
            image: client:latest
            entrypoint: /client
            environment:
                - CLI_ID=1
                - CLI_NOMBRE=Santiago Lionel
                - CLI_APELLIDO=Lorca
                - CLI_DOCUMENTO=30904465
                - CLI_NACIMIENTO=1999-03-17
                - CLI_NUMERO=7574
            volumes:
                - ./client/config.yaml:/config.yaml:ro
                - ./.data/agency-1.csv:/agency-1.csv:ro
            networks:
                - testing_net
            depends_on:
                - server
        
        client2:
            container_name: client2
            image: client:latest
            entrypoint: /client
            environment:
                - CLI_ID=2
                - CLI_NOMBRE=Santiago Lionel
                - CLI_APELLIDO=Lorca
                - CLI_DOCUMENTO=30904465
                - CLI_NACIMIENTO=1999-03-17
                - CLI_NUMERO=7574
            volumes:
                - ./client/config.yaml:/config.yaml:ro
                - ./.data/agency-2.csv:/agency-2.csv:ro
            networks:
                - testing_net
            depends_on:
                - server
        
    networks:
        testing_net:
            ipam:
                driver: default
                config:
                    - subnet: 172.25.125.0/24
    